server:
  port: 8080
  servlet:
    context-path: /api

spring:
  application:
    name: demo
  data:
    mongodb:
      host: localhost
      port: 27017
      database: JAVAApplication
      auto-index-creation: true

security:
  jwt:
    secret-key: test23874933Suraj/Kolhe/testSecretKeyForEncryption
    expiration-time: 3600000

whether:
  api:
    key: 2Wuq0LiJTRWaHwXaVUQmwJnVjx6hi3Fo
    url: https://api.tomorrow.io/v4/weather/forecast?location=LOCATION&apikey=API_KEY

#logging:
#  level:
#    com:
#      example:
#        demo: DEBUG
